image: "rust:latest"

stages:
    - lint

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo

lint:fmt:
    stage: lint
    before_script:
        - rustup component add rustfmt
    script: cargo fmt -- --check

lint:clippy:
    stage: lint
    before_script:
        - apt update -yqq
        - apt install -yqq sudo clang libpq-dev
        - rustup component add clippy
        - rustup target add wasm32-unknown-unknown
    script: make clippy
