[package]
name = "oxfeed-api"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"

[dependencies]
actix = "0.10"
actix-cors = "0.5"
actix-web = "3.2"
actix-web-actors = "3.0"
base64 = "0.13"
bigdecimal = "0.2"
dotenv = "0.15"
env_logger = "0.8"
feed-rs = "0.5"
futures-util = "0.3"
hmac = "0.10"
jwt = "0.13"
log = "0.4"
opml = "0.3"
rayon = "1.5"
ring = "0.17.0-alpha.7"
scraper = "0.12"
single-instance = "0.3"
serde = "1.0"
serde_json = "1.0"
sha2 = "0.9"
tree_magic = "0.2"
url = "2.2"

[dependencies.attohttpc]
version = "0.16"
features = ["json"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.oxfeed-common]
version = "0.1"
path = "../common/"
features = ["back"]

[dependencies.elephantry]
version = "1.5"
features = ["date", "numeric", "uuid", "serde-support"]

[dependencies.uuid]
version = "0.8"
features = ["serde"]
